name: 'Identify docs for UI'
description: 'Extract copy out of docs for X UI'
runs:
  using: "composite"
  steps:
    # install python
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    # generate markdown files
    - name: Run script
      run: python $GITHUB_ACTION_PATH/../../../website/script/ui_copy.py
      shell: bash
