name: Deliver updated UI copy

# runs when changes get pushed to main or x-main
# can also be run manually
on:
  push:
    branches:
      - x-main
      - main
      - x-docs-ui # temp
  workflow_dispatch:

jobs:
  docs_ui_copy:
    runs-on: [self-hosted, imply-ubuntu-latest]
    steps:

    # check out docs repo
    - name: Checkout
      uses: actions/checkout@main
      with:
        path: imply-docs-saas

    # check out x repo
    - uses: actions/checkout@main
      with:
        path: x
        repository: implydata/x
        token: ${{ secrets.SYNC_API_TOKEN }}
        ref: try-marksy # temp

    # install python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # generate markdown files
    - run: python imply-docs-saas/website/script/ui_copy.py --crossref

    # if csv changed, create imply-docs-saas pr
    - name: Create Pull Request (docs)
      uses: peter-evans/create-pull-request@v7
      with:
        base: x-docs-ui # temp, will be x-main
        token: ${{ secrets.REPO_PAT }}
        path: imply-docs-saas
        add-paths: |
          x_ui_copy.csv
        commit-message: "update CSV from deliver workflow"
        branch: "copy_update"
        delete-branch: true
        title: "x: Update UI copy reference file"
        body: |
          Updates x_ui_copy.csv.
          PR auto-generated by
          [create-pull-request](https://github.com/peter-evans/create-pull-request)

    # sync (overwrite) snippets to x
    - run: |
        mkdir -p x/ui-app/docs/src/markdown
        rm x/ui-app/docs/src/markdown/*
        cp -r imply-docs-saas/temp_ui_copy/* x/ui-app/docs/src/markdown/

    # install npm to run next script
    - run: cd x && npm install && npm install he

    # run the builder script
    - run: cd x/ui-app/docs && npm run buildmarkdown

    # create x pr
    - name: Create Pull Request (x)
      uses: peter-evans/create-pull-request@v7
      with:
        base: try-marksy # temp, will be main
        token: ${{ secrets.SYNC_API_TOKEN }}
        path: x
        add-paths: |
          ui-app/docs
        commit-message: "Sync copy from imply-docs-saas"
        branch: "docs-sync"
        delete-branch: true
        title: "docs: Update copy"
        assignees: vtlim
        reviewers: vtlim, teddyty
        body: |
          Update copy
          - Syncs from docs in [imply-docs-saas][1]
          - Auto-generated by [create-pull-request][2]

          [1]: https://github.com/implydata/imply-docs-saas/tree/x-main/x
          [2]: https://github.com/peter-evans/create-pull-request
