name: Copy Manager doc to imply-docs-saas
on:
  push:
    branches:
      - master
    paths:
      - 'website/manager/api-reference.html'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          CONFIG_PATH: '.github/cp-manager.yml'
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_BODY: "**Don't merge this PR into main until the STS release**"
          COMMIT_PREFIX: "STS: [Cloud Manager API]"
