name: Copy Polaris doc to imply-docs-saas
on:
  push:
    branches:
      - master
    paths:
      - 'website/polaris/api-reference.html'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          CONFIG_PATH: '.github/cp-polaris.yml'
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_PREFIX: "Polaris: [API reference]"
