name: Sync Cloud Manager API
on:
  schedule:
    - cron: '45 22 * * 1-5'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Get latest SHA of imply-cloud
      - name: Check latest SHA in imply-cloud
        uses: actions/checkout@v3
        with:
          repository: implydata/imply-cloud
          ref: master
          token: ${{ secrets.SYNC_API_TOKEN }}
          path: imply-cloud
      - name: Declare latest SHA variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=imply_cloud_sha::$(git -C imply-cloud rev-parse HEAD)"

      # Patch sync file
      - name: Checkout imply-docs-api
        uses: actions/checkout@v3
        with:
          repository: implydata/imply-docs-api
      - name: Patch sync file with new version
        run: |
          sed -i -E 's/(imply_cloud_revision)=".+"/\1="${{ steps.vars.outputs.imply_cloud_sha }}"/' scripts/sync

      # Make sure we're building the right file
      # like scripts/preprocess but for ubuntu
      - name: Preprocess scripts
        run: |
          sed -i 's/root:.*/root: .\/schemas\/merged-upstream-manager.yaml/g' redocly.yaml

          printf "mkdir -p dist/manager"\
          "\nmv dist/*.yaml dist/manager"\
          "\nmkdir -p website/manager"\
          "\nmv website/*.html website/manager" > scripts/postprocess
          chmod +x scripts/postprocess

      # Run the sync script
      - name: Sync API definitions
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          GITHUB_OAUTH_TOKEN=${{ secrets.SYNC_API_TOKEN }} npm run sync-remote-manager

      # Create a pull request containing the new sync if there are changes
      - name: Detect schema changes
        id: schema_changes
        continue-on-error: true # Exit code 1 (failure) means there _are_ changes
        run: |
          git diff --quiet schemas
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.schema_changes.outcome == 'failure' }}
        with:
          title: '[Manager] Update spec from imply-cloud'
          add-paths: |
            schemas/
            scripts/sync
          commit-message: Update report
          branch-suffix: timestamp
          delete-branch: true
          labels: |
            sync
          team-reviewers: |
            @implydata/techdocs
          token: ${{ secrets.SYNC_API_TOKEN }}
