name: "PR Conventional Commit Validation"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:

    validate-pr-title:
      runs-on: [self-hosted, imply-ubuntu-latest]
      steps:
        - name: PR Conventional Commit Validation
          uses:  ytanikin/pr-conventional-commits@1.4.0
          with:
            task_types: '["fix","FIX", "revert", "STS", "sts", "LTS", "lts", "POL", "pol", "x", "infra"]'
            add_label: 'false'
