name: Deliver updated UI copy

# runs when changes get pushed to main or x-main
# can also be run manually
on:
  push:
    branches:
      - x-main
      - main
      - x-docs-ui # temp
  workflow_dispatch:

jobs:
  docs_ui_copy:
    runs-on: [self-hosted, imply-ubuntu-latest]
    steps:

    # check out docs repo
    - name: Checkout
      uses: actions/checkout@main
      with:
        path: imply-docs-saas

    # check out x repo
    - uses: actions/checkout@main
      with:
        path: x
        repository: implydata/x
        token: ${{ secrets.SYNC_API_TOKEN }}
        ref: try-marksy # temp

    # install python and process markdown files
    - uses: ./imply-docs-saas/.github/actions/ui_copy

    # copy over to x, overwriting any existing snippets
    - run: |
        mkdir -p x/some-path/docs/src/markdown
        rm x/some-path/docs/src/markdown/*
        cp -r imply-docs-saas/temp_ui_copy/* x/some-path/docs/src/markdown/

    # install npm to run next script
    - run: cd x && npm install

    # run the builder script
    - run: cd x/some-path/docs && npm run buildmarkdown

    # create x pr
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        base: try-marksy # temp
        token: ${{ secrets.SYNC_API_TOKEN }}
        path: iow
        add-paths: |
          some-path/docs
        commit-message: "Sync copy from imply-docs-saas"
        branch: "docs-sync"
        delete-branch: true
        title: "docs: Update copy"
        assignees: vtlim
        reviewers: vtlim, teddyty
        body: |
          Update copy
          - Syncs from docs in [imply-docs-saas][1]
          - Auto-generated by [create-pull-request][2]

          [1]: https://github.com/implydata/imply-docs-saas/tree/x-main/x
          [2]: https://github.com/peter-evans/create-pull-request
